#!/bin/sh

. /lib/functions/system.sh

[ "$(board_name 2>/dev/null)" = "jdcloud,ax1800-pro" ] || exit 0

uci -q batch <<'EOF'
set network.lan.ifname='eth0 eth1 eth2 eth3'
set network.lan.type='bridge'
delete network.lan.ip6assign

set network.wan.ifname='usb0'
set network.wan.proto='dhcp'

delete network.wan6
set network.wan6='interface'
set network.wan6.ifname='usb0'
set network.wan6.proto='dhcpv6'
set network.wan6.reqaddress='try'
set network.wan6.reqprefix='no'
EOF

uci commit network

uci -q batch <<'EOF'
set dhcp.lan.ra='relay'
set dhcp.lan.dhcpv6='relay'
set dhcp.lan.ndp='relay'

delete dhcp.wan
set dhcp.wan='dhcp'
set dhcp.wan.interface='wan'
set dhcp.wan.ignore='1'

delete dhcp.wan6
set dhcp.wan6='dhcp'
set dhcp.wan6.interface='wan6'
set dhcp.wan6.ignore='1'
set dhcp.wan6.ra='relay'
set dhcp.wan6.dhcpv6='relay'
set dhcp.wan6.ndp='relay'
set dhcp.wan6.master='1'
EOF

uci commit dhcp

exit 0
